import {StyleSheet, Dimensions} from 'react-native';
import {Colors} from '@constants/Colors';
import {IColors, IStyles} from '@constants/Interfaces';

const maxHeight = Dimensions.get('window').height;
const maxWidth = Dimensions.get('window').width;

const Styles = (colors: IColors): IStyles =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors?.light,
    },

    flex: {flex: 1, backgroundColor: colors?.light},
    cP: {color: colors?.primary},
    cS: {color: colors?.secondary},
    cSuccess: {color: colors?.success},
    cDanger: {color: colors?.danger},
    cWarning: {color: colors?.warning},
    cInfo: {color: colors?.info},
    cDark: {color: colors?.dark},
    cLight: {color: colors?.light},

    screen_W: {width: maxWidth},
    screen_H: {height: maxHeight},

    w_5: {width: '5%'},
    w_10: {width: '10%'},
    w_15: {width: '15%'},
    w_18: {width: '18%'},
    w_20: {width: '20%'},
    w_25: {width: '25%'},
    w_30: {width: '30%'},
    w_33: {width: '33.33%'},
    w_35: {width: '35%'},
    w_40: {width: '40%'},
    w_45: {width: '45%'},
    w_48: {width: '48%'},
    w_49: {width: '49%'},
    w_50: {width: '50%'},
    w_55: {width: '55%'},
    w_60: {width: '60%'},
    w_65: {width: '65%'},
    w_70: {width: '70%'},
    w_75: {width: '75%'},
    w_80: {width: '80%'},
    w_85: {width: '85%'},
    w_90: {width: '90%'},
    w_95: {width: '95%'},
    w_100: {width: '100%'},

    h_5: {height: '5%'},
    h_10: {height: '10%'},
    h_15: {height: '15%'},
    h_20: {height: '20%'},
    h_25: {height: '25%'},
    h_30: {height: '30%'},
    h_35: {height: '35%'},
    h_40: {height: '40%'},
    h_50: {height: '50%'},
    h_55: {height: '55%'},
    h_60: {height: '60%'},
    h_65: {height: '65%'},
    h_70: {height: '70%'},
    h_75: {height: '75%'},
    h_80: {height: '80%'},
    h_90: {height: '90%'},
    h_95: {height: '95%'},
    h_100: {height: '100%'},

    p4: {padding: 4},
    p5: {padding: 5},
    p8: {padding: 8},
    p10: {padding: 10},
    p15: {padding: 15},
    p16: {padding: 16},
    p20: {padding: 20},
    p24: {padding: 24},
    p25: {padding: 25},
    p30: {padding: 30},
    p32: {padding: 32},
    p35: {padding: 35},
    p40: {padding: 40},
    p48: {padding: 48},
    p50: {padding: 50},
    p60: {padding: 60},
    p64: {padding: 64},
    p70: {padding: 70},
    p80: {padding: 80},
    p90: {padding: 90},
    p96: {padding: 96},
    p100: {padding: 100},

    pt_4: {paddingTop: 4},
    pt_8: {paddingTop: 8},
    pt_16: {paddingTop: 16},
    pt_24: {paddingTop: 24},
    pt_32: {paddingTop: 32},
    pt_40: {paddingTop: 40},
    pt_48: {paddingTop: 48},
    pt_64: {paddingTop: 64},
    pt_96: {paddingTop: 96},

    pl_4: {paddingLeft: 4},
    pl_8: {paddingLeft: 8},
    pl_16: {paddingLeft: 16},
    pl_24: {paddingLeft: 24},
    pl_32: {paddingLeft: 32},
    pl_40: {paddingLeft: 40},
    pl_48: {paddingLeft: 48},
    pl_64: {paddingLeft: 64},
    pl_96: {paddingLeft: 96},

    pr_4: {paddingRight: 4},
    pr_8: {paddingRight: 8},
    pr_16: {paddingRight: 16},
    pr_24: {paddingRight: 24},
    pr_32: {paddingRight: 32},
    pr_40: {paddingRight: 40},
    pr_48: {paddingRight: 48},
    pr_64: {paddingRight: 64},
    pr_96: {paddingRight: 96},

    pb_4: {paddingBottom: 4},
    pb_8: {paddingBottom: 8},
    pb_16: {paddingBottom: 16},
    pb_24: {paddingBottom: 24},
    pb_32: {paddingBottom: 32},
    pb_48: {paddingBottom: 48},
    pb_64: {paddingBottom: 64},
    pb_96: {paddingBottom: 96},

    py_4: {paddingVertical: 4},
    py_8: {paddingVertical: 8},
    py_16: {paddingVertical: 16},
    py_24: {paddingVertical: 24},
    py_32: {paddingVertical: 32},
    py_40: {paddingVertical: 40},
    py_48: {paddingVertical: 48},
    py_64: {paddingVertical: 64},
    py_96: {paddingVertical: 96},
    px_4: {paddingHorizontal: 4},
    px_8: {paddingHorizontal: 8},
    px_16: {paddingHorizontal: 16},
    px_24: {paddingHorizontal: 24},
    px_32: {paddingHorizontal: 32},
    px_40: {paddingHorizontal: 40},
    px_48: {paddingHorizontal: 48},
    px_64: {paddingHorizontal: 64},
    px_96: {paddingHorizontal: 96},

    pt_5: {paddingTop: 5},
    pt_10: {paddingTop: 10},
    pt_12: {paddingTop: 12},
    pt_15: {paddingTop: 15},
    pt_20: {paddingTop: 20},
    pt_25: {paddingTop: 25},
    pt_30: {paddingTop: 30},
    pt_35: {paddingTop: 35},
    pt_50: {paddingTop: 50},
    pt_60: {paddingTop: 60},
    pt_70: {paddingTop: 70},
    pt_80: {paddingTop: 80},
    pt_90: {paddingTop: 90},
    pt_100: {paddingTop: 100},

    pb_5: {paddingBottom: 5},
    pb_10: {paddingBottom: 10},
    pb_12: {paddingBottom: 12},
    pb_15: {paddingBottom: 15},
    pb_20: {paddingBottom: 20},
    pb_25: {paddingBottom: 25},
    pb_30: {paddingBottom: 30},
    pb_35: {paddingBottom: 35},
    pb_40: {paddingBottom: 40},
    pb_50: {paddingBottom: 50},
    pb_60: {paddingBottom: 60},
    pb_70: {paddingBottom: 70},
    pb_80: {paddingBottom: 80},
    pb_90: {paddingBottom: 90},
    pb_100: {paddingBottom: 100},

    pl_5: {paddingLeft: 5},
    pl_10: {paddingLeft: 10},
    pl_15: {paddingLeft: 15},
    pl_20: {paddingLeft: 20},
    pl_25: {paddingLeft: 25},
    pl_30: {paddingLeft: 30},
    pl_35: {paddingLeft: 35},
    pl_50: {paddingLeft: 50},
    pl_60: {paddingLeft: 60},
    pl_70: {paddingLeft: 70},
    pl_80: {paddingLeft: 80},
    pl_90: {paddingLeft: 90},
    pl_100: {paddingLeft: 100},

    pr_5: {paddingRight: 5},
    pr_10: {paddingRight: 10},
    pr_15: {paddingRight: 15},
    pr_20: {paddingRight: 20},
    pr_25: {paddingRight: 25},
    pr_30: {paddingRight: 30},
    pr_35: {paddingRight: 35},
    pr_50: {paddingRight: 50},
    pr_60: {paddingRight: 60},
    pr_70: {paddingRight: 70},
    pr_80: {paddingRight: 80},
    pr_90: {paddingRight: 90},
    pr_100: {paddingRight: 100},

    py_5: {paddingVertical: 5},
    py_10: {paddingVertical: 10},
    py_12: {paddingVertical: 12},
    py_15: {paddingVertical: 15},
    py_20: {paddingVertical: 20},
    py_25: {paddingVertical: 25},
    py_30: {paddingVertical: 30},
    py_35: {paddingVertical: 35},
    py_50: {paddingVertical: 50},
    py_60: {paddingVertical: 60},
    py_70: {paddingVertical: 70},
    py_80: {paddingVertical: 80},
    py_90: {paddingVertical: 90},
    py_100: {paddingVertical: 100},

    px_5: {paddingHorizontal: 5},
    px_10: {paddingHorizontal: 10},
    px_15: {paddingHorizontal: 15},
    px_20: {paddingHorizontal: 20},
    px_25: {paddingHorizontal: 25},
    px_30: {paddingHorizontal: 30},
    px_35: {paddingHorizontal: 35},
    px_50: {paddingHorizontal: 50},
    px_60: {paddingHorizontal: 60},
    px_70: {paddingHorizontal: 70},
    px_80: {paddingHorizontal: 80},
    px_90: {paddingHorizontal: 90},
    px_100: {paddingHorizontal: 100},

    m4: {margin: 4},
    m5: {margin: 5},
    m8: {margin: 8},
    m10: {margin: 10},
    m15: {margin: 15},
    m16: {margin: 16},
    m20: {margin: 20},
    m24: {margin: 24},
    m25: {margin: 25},
    m30: {margin: 30},
    m32: {margin: 32},
    m35: {margin: 35},
    m40: {margin: 40},
    m48: {margin: 48},
    m50: {margin: 50},
    m60: {margin: 60},
    m64: {margin: 64},
    m70: {margin: 70},
    m80: {margin: 80},
    m90: {margin: 90},
    m96: {margin: 96},
    m100: {margin: 100},

    mt_4: {marginTop: 4},
    mt_5: {marginTop: 5},
    mt_8: {marginTop: 8},
    mt_10: {marginTop: 10},
    mt_15: {marginTop: 15},
    mt_16: {marginTop: 16},
    mt_24: {marginTop: 24},
    mt_32: {marginTop: 32},
    mt_40: {marginTop: 40},
    mt_48: {marginTop: 48},
    mt_64: {marginTop: 64},
    mt_96: {marginTop: 96},

    mt_25: {marginTop: 25},
    mt_30: {marginTop: 30},
    mt_35: {marginTop: 35},
    mt_50: {marginTop: 50},
    mt_60: {marginTop: 60},
    mt_70: {marginTop: 70},
    mt_80: {marginTop: 80},
    mt_90: {marginTop: 90},
    mt_100: {marginTop: 100},

    ml_4: {marginLeft: 4},
    ml_8: {marginLeft: 8},
    ml_16: {marginLeft: 16},
    ml_24: {marginLeft: 24},
    ml_32: {marginLeft: 32},
    ml_40: {marginLeft: 40},
    ml_48: {marginLeft: 48},
    ml_64: {marginLeft: 64},
    ml_96: {marginLeft: 96},

    mr_4: {marginRight: 4},
    mr_8: {marginRight: 8},
    mr_16: {marginRight: 16},
    mr_24: {marginRight: 24},
    mr_32: {marginRight: 32},
    mr_40: {marginRight: 40},
    mr_48: {marginRight: 48},
    mr_64: {marginRight: 64},
    mr_96: {marginRight: 96},

    mb_4: {marginBottom: 4},
    mb_8: {marginBottom: 8},
    mb_16: {marginBottom: 16},
    mb_24: {marginBottom: 24},
    mb_32: {marginBottom: 32},
    mb_40: {marginBottom: 40},
    mb_48: {marginBottom: 48},
    mb_64: {marginBottom: 64},
    mb_96: {marginBottom: 96},

    my_4: {marginVertical: 4},
    my_8: {marginVertical: 8},
    my_16: {marginVertical: 16},
    my_24: {marginVertical: 24},
    my_32: {marginVertical: 32},
    my_40: {marginVertical: 40},
    my_48: {marginVertical: 48},
    my_64: {marginVertical: 64},
    my_96: {marginVertical: 96},

    mx_4: {marginHorizontal: 4},
    mx_8: {marginHorizontal: 8},
    mx_16: {marginHorizontal: 16},
    mx_24: {marginHorizontal: 24},
    mx_32: {marginHorizontal: 32},
    mx_40: {marginHorizontal: 40},
    mx_48: {marginHorizontal: 48},
    mx_64: {marginHorizontal: 64},
    mx_96: {marginHorizontal: 96},

    mb_5: {marginBottom: 5},
    mb_10: {marginBottom: 10},
    mb_15: {marginBottom: 15},
    mb_20: {marginBottom: 20},
    mb_25: {marginBottom: 25},
    mb_30: {marginBottom: 30},
    mb_35: {marginBottom: 35},
    mb_45: {marginBottom: 45},
    mb_50: {marginBottom: 50},
    mb_60: {marginBottom: 60},
    mb_70: {marginBottom: 70},
    mb_80: {marginBottom: 80},
    mb_90: {marginBottom: 90},
    mb_100: {marginBottom: 100},

    ml_5: {marginLeft: 5},
    ml_10: {marginLeft: 10},
    ml_15: {marginLeft: 15},
    ml_20: {marginLeft: 20},
    ml_25: {marginLeft: 25},
    ml_30: {marginLeft: 30},
    ml_35: {marginLeft: 35},
    ml_50: {marginLeft: 50},
    ml_60: {marginLeft: 60},
    ml_70: {marginLeft: 70},
    ml_80: {marginLeft: 80},
    ml_90: {marginLeft: 90},
    ml_100: {marginLeft: 100},

    mr_5: {marginRight: 5},
    mr_10: {marginRight: 10},
    mr_15: {marginRight: 15},
    mr_20: {marginRight: 20},
    mr_25: {marginRight: 25},
    mr_30: {marginRight: 30},
    mr_35: {marginRight: 35},
    mr_50: {marginRight: 50},
    mr_60: {marginRight: 60},
    mr_70: {marginRight: 70},
    mr_80: {marginRight: 80},
    mr_90: {marginRight: 90},
    mr_100: {marginRight: 100},

    my_5: {marginVertical: 5},
    my_10: {marginVertical: 10},
    my_15: {marginVertical: 15},
    my_20: {marginVertical: 20},
    my_25: {marginVertical: 25},
    my_30: {marginVertical: 30},
    my_35: {marginVertical: 35},
    my_50: {marginVertical: 50},
    my_60: {marginVertical: 60},
    my_70: {marginVertical: 70},
    my_80: {marginVertical: 80},
    my_90: {marginVertical: 90},
    my_100: {marginVertical: 100},

    mx_5: {marginHorizontal: 5},
    mx_10: {marginHorizontal: 10},
    mx_15: {marginHorizontal: 15},
    mx_20: {marginHorizontal: 20},
    mx_25: {marginHorizontal: 25},
    mx_30: {marginHorizontal: 30},
    mx_35: {marginHorizontal: 35},
    mx_50: {marginHorizontal: 50},
    mx_60: {marginHorizontal: 60},
    mx_70: {marginHorizontal: 70},
    mx_80: {marginHorizontal: 80},
    mx_90: {marginHorizontal: 90},
    mx_100: {marginHorizontal: 100},

    ta_center: {textAlign: 'center'},
    ta_justify: {textAlign: 'justify'},
    ta_right: {textAlign: 'right'},
    ta_left: {textAlign: 'left'},

    bold: {fontWeight: 'bold'},
    bold4: {fontWeight: '400'},
    bold5: {fontWeight: '500'},
    bold6: {fontWeight: '600'},
    bold7: {fontWeight: '700'},
    strick: {textDecorationLine: 'line-through'},
    underline: {textDecorationLine: 'underline'},

    heading: {
      fontSize: 20,
      fontFamily: Colors?.fontSemiBold,
      textTransform: 'capitalize',
      textAlign: colors?.RTL ? 'right' : 'left',
      color: colors?.dark,
    },
    title: {
      fontSize: 16,
      color: colors?.dark,
      fontFamily: colors?.fontMedium,
      textTransform: 'capitalize',
      textAlign: colors?.RTL ? 'right' : 'left',
    },
    subTitle: {
      fontSize: 14,
      color: colors?.gray,
      fontFamily: colors?.fontMedium,
      // textTransform: 'capitalize',
      textAlign: colors?.RTL ? 'right' : 'left',
    },
    darkText: {
      fontSize: 14,
      color: colors?.dark,
      fontFamily: colors?.fontMedium,
      // textTransform: 'capitalize',
      textAlign: colors?.RTL ? 'right' : 'left',
    },
    simpleText: {
      color: colors?.primary,
      fontFamily: colors?.fontMedium,
      fontSize: 14,
      // textTransform: 'capitalize',
      textAlign: colors?.RTL ? 'right' : 'left',
    },
    descriptionText: {
      fontSize: 12,
      fontFamily: colors?.font,
      color: colors?.gray,
      // textTransform: 'capitalize',
      textAlign: colors?.RTL ? 'right' : 'left',
    },
    smallText: {
      fontSize: 10,
      fontFamily: colors?.fontMedium,
      // textTransform: 'capitalize',
      color: colors?.gray,
      textAlign: colors?.RTL ? 'right' : 'left',
    },
    emailText: {
      fontSize: 12,
      fontFamily: colors?.fontMedium,
      textTransform: 'lowercase',
      color: colors?.primary,
      textDecorationLine: 'underline',
      textAlign: colors?.RTL ? 'right' : 'left',
    },
    errorText: {
      fontSize: 10,
      marginTop: 2,
      marginHorizontal: 8,
      fontFamily: colors?.fontSemiBold,
      color: colors?.danger,
    },

    tx9: {fontSize: 9, color: Colors?.textDark, fontFamily: Colors?.font},
    tx10: {fontSize: 10, color: Colors?.textDark, fontFamily: Colors?.font},
    tx11: {fontSize: 11, color: Colors?.textDark, fontFamily: Colors?.font},
    tx12: {fontSize: 12, color: Colors?.textDark, fontFamily: Colors?.font},
    tx13: {fontSize: 13, color: Colors?.textDark, fontFamily: Colors?.font},
    tx14: {fontSize: 14, color: Colors?.textDark, fontFamily: Colors?.font},
    tx16: {fontSize: 16, color: Colors?.textDark, fontFamily: Colors?.font},
    tx18: {fontSize: 18, color: Colors?.textDark, fontFamily: Colors?.font},
    tx20: {fontSize: 20, color: Colors?.textDark, fontFamily: Colors?.font},
    tx22: {fontSize: 22, color: Colors?.textDark, fontFamily: Colors?.font},
    tx24: {fontSize: 24, color: Colors?.textDark, fontFamily: Colors?.font},
    tx26: {fontSize: 26, color: Colors?.textDark, fontFamily: Colors?.font},
    tx28: {fontSize: 28, color: Colors?.textDark, fontFamily: Colors?.font},
    tx30: {fontSize: 30, color: Colors?.textDark, fontFamily: Colors?.font},
    tx36: {fontSize: 36, color: Colors?.textDark, fontFamily: Colors?.font},

    line_h_18: {lineHeight: 18},

    row: {flexDirection: colors?.RTL ? 'row-reverse' : 'row'},
    row_reverse: {flexDirection: 'row-reverse'},
    column: {flexDirection: 'column'},
    column_reverse: {flexDirection: 'column-reverse'},

    flex_wrap: {flexWrap: 'wrap'},

    jc_al_center: {justifyContent: 'center', alignItems: 'center'},

    jc_center: {justifyContent: 'center'},
    jc_space_around: {justifyContent: 'space-around'},
    jc_space_between: {justifyContent: 'space-between'},

    ai_center: {alignItems: 'center'},
    ai_flex_end: {alignItems: 'flex-end'},
    ai_flex_start: {alignItems: 'flex-start'},
    ai_stretch: {alignItems: 'stretch'},

    as_center: {alignSelf: 'center'},
    as_flex_end: {alignSelf: 'flex-end'},
    as_flex_start: {alignSelf: 'flex-start'},
    as_stretch: {alignSelf: 'stretch'},

    circle: {borderRadius: 200, overflow: 'hidden'},
    card: {
      minHeight: 45,
      marginBottom: 16,
      backgroundColor: colors?.light,
      padding: 8,
      borderRadius: 16,
      marginHorizontal: 8,
      shadowColor: colors?.dark,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    card1: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors?.whiteLight,
      paddingHorizontal: 16,
      borderRadius: 8,
      flex: 1,
      marginHorizontal: 8,
      marginVertical: 1,

      shadowColor: colors?.dark,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,

      elevation: 5,
    },
    inputGrey: {
      marginTop: 16,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      height: 50,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderRadius: 8,
      borderColor: colors?.lightGray,
      backgroundColor: colors?.whiteLight,
    },
    modalDivider: {
      marginTop: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors?.gray,
    },
    smallBtnIcon: {
      height: 34,
      paddingHorizontal: 8,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors?.primary,
      borderRadius: 8,
    },
  });

export default Styles;
